DECLARE
 NCOUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'TEACHER';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE TEACHER(
      TEACHER_ID INTEGER PRIMARY KEY,
      NAME       VARCHAR(30) NOT NULL,
      POSITION   VARCHAR(40))';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'SUBJECT';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE SUBJECT(
      SUBJECT_ID INTEGER PRIMARY KEY,
      NAME       VARCHAR(30))';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'CLASS';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE CLASS(
      CLASS_ID INTEGER PRIMARY KEY,
      GRADE    INTEGER,
      NAME     VARCHAR(30))';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'PUPIL';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE TABLE PUPIL(
      PUPIL_ID INTEGER PRIMARY KEY,
      CLASS_ID INTEGER,
      NAME     VARCHAR(30))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE PUPIL
     ADD CONSTRAINT FK_PUPIL FOREIGN KEY (CLASS_ID) 
     REFERENCES CLASS (CLASS_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'SCHOOL_YEAR';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE SCHOOL_YEAR(
                                   SCHOOL_YEAR_ID INTEGER PRIMARY KEY,
                                   NAME        VARCHAR(100),
                                   START_DATE  DATE,
                                   END_DATE    DATE)';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'SEMESTER';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE SEMESTER(
                                   SEMESTER_ID    INTEGER PRIMARY KEY,
                                   SCHOOL_YEAR_ID INTEGER,
                                   NAME           VARCHAR(100),
                                   START_DATE     DATE,
                                   END_DATE       DATE)';
     EXECUTE IMMEDIATE
         'ALTER TABLE SEMESTER
             ADD CONSTRAINT FK_SEMESTER FOREIGN KEY (SCHOOL_YEAR_ID)
                 REFERENCES SCHOOL_YEAR (SCHOOL_YEAR_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'SUBJECT_DETAILS';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE SUBJECT_DETAILS(
      SUBJECT_DETAILS_ID INTEGER PRIMARY KEY,
      CLASS_ID           INTEGER,
      TEACHER_ID         INTEGER,
      SUBJECT_ID         INTEGER,
      SEMESTER_ID        INTEGER,
      CONSTRAINT SUBJECT_DETAILS_UNIQUE UNIQUE (CLASS_ID, SUBJECT_ID, SEMESTER_ID))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE SUBJECT_DETAILS
	 ADD CONSTRAINT FK_SUBJECT_DETAILS1 FOREIGN KEY (CLASS_ID) 
	 REFERENCES CLASS (CLASS_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE SUBJECT_DETAILS
	 ADD CONSTRAINT FK_SUBJECT_DETAILS2 FOREIGN KEY (TEACHER_ID) 
	 REFERENCES TEACHER (TEACHER_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE SUBJECT_DETAILS
	 ADD CONSTRAINT FK_SUBJECT_DETAILS3 FOREIGN KEY (SUBJECT_ID) 
	 REFERENCES SUBJECT (SUBJECT_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE
       'ALTER TABLE SUBJECT_DETAILS
           ADD CONSTRAINT FK_SUBJECT_DETAILS4 FOREIGN KEY (SEMESTER_ID)
               REFERENCES SEMESTER (SEMESTER_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'THEME';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE THEME(
                            THEME_ID           INTEGER PRIMARY KEY,
                            SUBJECT_DETAILS_ID INTEGER,
                            NAME               VARCHAR(100))';
     EXECUTE IMMEDIATE
         'ALTER TABLE THEME
             ADD CONSTRAINT FK_THEME1 FOREIGN KEY (SUBJECT_DETAILS_ID)
                 REFERENCES SUBJECT_DETAILS (SUBJECT_DETAILS_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LESSON';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LESSON(
      LESSON_ID   INTEGER PRIMARY KEY,
      THEME_ID    INTEGER,
      LESSON_DATE DATE,
      TOPIC       VARCHAR(100))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LESSON
     ADD CONSTRAINT FK_LESSON FOREIGN KEY (THEME_ID)
	 REFERENCES THEME (THEME_ID) ON DELETE CASCADE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'MARK';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE MARK(
      MARK_ID   INTEGER PRIMARY KEY,
      PUPIL_ID  INTEGER,
      LESSON_ID INTEGER,
      MARK      INTEGER,
      CONSTRAINT MARK_UNIQUE UNIQUE (PUPIL_ID, LESSON_ID))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE MARK
	 ADD CONSTRAINT FK_MARK1 FOREIGN KEY (PUPIL_ID) 
	 REFERENCES PUPIL (PUPIL_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE MARK
	 ADD CONSTRAINT FK_MARK2 FOREIGN KEY (LESSON_ID) 
	 REFERENCES LESSON (LESSON_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'GRADEBOOK_USER';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE GRADEBOOK_USER(
            USER_ID  INTEGER primary key,
            USERNAME VARCHAR(50),
            PASSWORD VARCHAR(200))';
     EXECUTE IMMEDIATE 'INSERT INTO GRADEBOOK_USER VALUES (1, ''ADMIN'', ''$2a$10$ADnVWXeK4NXJqMGbgU4qv.m9npqvxRIu7LR1fzjCLMa5UNuvHZakC'')';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'ROLE';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE ROLE(
            ROLE_ID  INTEGER primary key,
            NAME     VARCHAR(20))';
     EXECUTE IMMEDIATE 'INSERT INTO ROLE VALUES (1, ''ADMIN'')';
     EXECUTE IMMEDIATE 'INSERT INTO ROLE VALUES (2, ''TEACHER'')';
     EXECUTE IMMEDIATE 'INSERT INTO ROLE VALUES (3, ''PUPIL'')';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'USER_ROLE';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE USER_ROLE(
            USER_ID INTEGER,
            ROLE_ID INTEGER)';
     EXECUTE IMMEDIATE
         'ALTER TABLE USER_ROLE
             ADD CONSTRAINT FK_USER_ROLE1 FOREIGN KEY (USER_ID)
                 REFERENCES GRADEBOOK_USER (USER_ID) ON DELETE CASCADE';
     EXECUTE IMMEDIATE
         'ALTER TABLE USER_ROLE
             ADD CONSTRAINT FK_USER_ROLE2 FOREIGN KEY (ROLE_ID)
                 REFERENCES ROLE (ROLE_ID) ON DELETE CASCADE';
     EXECUTE IMMEDIATE
         'INSERT INTO USER_ROLE VALUES (1, 1)';

 END IF;


 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'SUBJECT_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE SUBJECT_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'CLASS_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE CLASS_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'SUBJECT_DETAILS_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE SEQUENCE SUBJECT_DETAILS_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LESSON_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LESSON_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'MARK_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE SEQUENCE MARK_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'USER_SEQ';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE SEQUENCE USER_SEQ
             MINVALUE 2
             START WITH 2
             INCREMENT BY 1
             NOCACHE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'THEME_SEQ';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE SEQUENCE THEME_SEQ
             MINVALUE 1
             START WITH 1
             INCREMENT BY 1
             NOCACHE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'SCHOOL_YEAR_SEQ';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE SEQUENCE SCHOOL_YEAR_SEQ
             MINVALUE 1
             START WITH 1
             INCREMENT BY 1
             NOCACHE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'SEMESTER_SEQ';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE SEQUENCE SEMESTER_SEQ
             MINVALUE 1
             START WITH 1
             INCREMENT BY 1
             NOCACHE';
 END IF;

 EXECUTE IMMEDIATE
 'CREATE OR REPLACE TRIGGER TEACHER_INSERT
AFTER insert on TEACHER
 FOR EACH ROW
 begin
     insert into GRADEBOOK_USER values(:new.TEACHER_ID, :new.NAME||:new.TEACHER_ID, :new.NAME||:new.TEACHER_ID);
    insert into USER_ROLE values (:new.TEACHER_ID, 2);
 end;';

 EXECUTE IMMEDIATE
     'CREATE OR REPLACE TRIGGER PUPIL_INSERT
         AFTER insert on PUPIL
         FOR EACH ROW
     begin
         insert into GRADEBOOK_USER values(:new.PUPIL_ID, :new.NAME||:new.PUPIL_ID, :new.NAME||:new.PUPIL_ID);
         insert into USER_ROLE values (:new.PUPIL_ID, 3);
     end;';
END;
