DECLARE
 NCOUNT NUMBER;
BEGIN
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_TEACHER';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_TEACHER(
      TEACHER_ID INTEGER PRIMARY KEY,
      NAME       VARCHAR(30) NOT NULL,
      POSITION   VARCHAR(40),
      CHIEF      INTEGER)';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_TEACHER 
     ADD CONSTRAINT FK_SELF FOREIGN KEY (CHIEF) 
     REFERENCES LAB3_ROZGHON_TEACHER (TEACHER_ID) ON DELETE CASCADE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_SUBJECT';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_SUBJECT(
      SUBJECT_ID INTEGER PRIMARY KEY,
      NAME       VARCHAR(30))';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_CLASS';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_CLASS(
      CLASS_ID INTEGER PRIMARY KEY,
      GRADE    INTEGER,
      NAME     VARCHAR(30))';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_PUPILS';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE TABLE LAB3_ROZGHON_PUPILS(
      PUPIL_ID INTEGER PRIMARY KEY,
      CLASS_ID INTEGER,
      NAME     VARCHAR(30))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_PUPILS 
     ADD CONSTRAINT FK_PUPIL FOREIGN KEY (CLASS_ID) 
     REFERENCES LAB3_ROZGHON_CLASS (CLASS_ID) ON DELETE CASCADE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_SUBJECT_DETAILS';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_SUBJECT_DETAILS(
      SUBJECT_DETAILS_ID INTEGER PRIMARY KEY,
      CLASS_ID           INTEGER,
      TEACHER_ID         INTEGER,
      SUBJECT_ID         INTEGER)';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_SUBJECT_DETAILS 
	 ADD CONSTRAINT FK_SUBJECT_DETAILS1 FOREIGN KEY (CLASS_ID) 
	 REFERENCES LAB3_ROZGHON_CLASS (CLASS_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_SUBJECT_DETAILS 
	 ADD CONSTRAINT FK_SUBJECT_DETAILS2 FOREIGN KEY (TEACHER_ID) 
	 REFERENCES LAB3_ROZGHON_TEACHER (TEACHER_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_SUBJECT_DETAILS 
	 ADD CONSTRAINT FK_SUBJECT_DETAILS3 FOREIGN KEY (SUBJECT_ID) 
	 REFERENCES LAB3_ROZGHON_SUBJECT (SUBJECT_ID) ON DELETE CASCADE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_LESSON';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_LESSON(
      LESSON_ID          INTEGER PRIMARY KEY,
      SUBJECT_DETAILS_ID INTEGER,
      LESSON_DATE        DATE,
      TOPIC              VARCHAR(30))';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_LESSON 
     ADD CONSTRAINT FK_LESSON FOREIGN KEY (SUBJECT_DETAILS_ID) 
	 REFERENCES LAB3_ROZGHON_SUBJECT_DETAILS (SUBJECT_DETAILS_ID) ON DELETE CASCADE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_MARK';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE TABLE LAB3_ROZGHON_MARK(
      MARK_ID   INTEGER PRIMARY KEY,
      PUPIL_ID  INTEGER,
      LESSON_ID INTEGER,
      MARK      INTEGER)';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_MARK 
	 ADD CONSTRAINT FK_MARK1 FOREIGN KEY (PUPIL_ID) 
	 REFERENCES LAB3_ROZGHON_PUPILS (PUPIL_ID) ON DELETE CASCADE';
   EXECUTE IMMEDIATE 
    'ALTER TABLE LAB3_ROZGHON_MARK 
	 ADD CONSTRAINT FK_MARK2 FOREIGN KEY (LESSON_ID) 
	 REFERENCES LAB3_ROZGHON_LESSON (LESSON_ID) ON DELETE CASCADE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_USER';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE LAB3_ROZGHON_USER(
            USER_ID  INTEGER primary key,
            USERNAME VARCHAR(50),
            PASSWORD VARCHAR(200))';
     EXECUTE IMMEDIATE 'INSERT INTO LAB3_ROZGHON_USER VALUES (1, ''ADMIN'', ''$2a$10$ADnVWXeK4NXJqMGbgU4qv.m9npqvxRIu7LR1fzjCLMa5UNuvHZakC'')';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_ROLE';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE LAB3_ROZGHON_ROLE(
            ROLE_ID  INTEGER primary key,
            NAME     VARCHAR(20))';
     EXECUTE IMMEDIATE 'INSERT INTO LAB3_ROZGHON_ROLE VALUES (1, ''ADMIN'')';
     EXECUTE IMMEDIATE 'INSERT INTO LAB3_ROZGHON_ROLE VALUES (2, ''TEACHER'')';
     EXECUTE IMMEDIATE 'INSERT INTO LAB3_ROZGHON_ROLE VALUES (3, ''PUPIL'')';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_TABLES WHERE TABLE_NAME = 'LAB3_ROZGHON_USER_ROLE';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE TABLE LAB3_ROZGHON_USER_ROLE(
            USER_ID INTEGER,
            ROLE_ID INTEGER)';
     EXECUTE IMMEDIATE
         'ALTER TABLE LAB3_ROZGHON_USER_ROLE
             ADD CONSTRAINT FK_USER_ROLE1 FOREIGN KEY (USER_ID)
                 REFERENCES LAB3_ROZGHON_USER (USER_ID) ON DELETE CASCADE';
     EXECUTE IMMEDIATE
         'ALTER TABLE LAB3_ROZGHON_USER_ROLE
             ADD CONSTRAINT FK_USER_ROLE2 FOREIGN KEY (ROLE_ID)
                 REFERENCES LAB3_ROZGHON_ROLE (ROLE_ID) ON DELETE CASCADE';
     EXECUTE IMMEDIATE
         'INSERT INTO LAB3_ROZGHON_USER_ROLE VALUES (1, 1)';

 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_TEACHER_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LAB3_ROZGHON_TEACHER_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
   END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_SUBJECT_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LAB3_ROZGHON_SUBJECT_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_CLASS_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LAB3_ROZGHON_CLASS_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_PUPILS_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LAB3_ROZGHON_PUPILS_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_SUBJECT_DETAILS_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE SEQUENCE LAB3_ROZGHON_SUBJECT_DETAILS_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_LESSON_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE 
    'CREATE SEQUENCE LAB3_ROZGHON_LESSON_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;
 
 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_MARK_SEQ';
 IF(NCOUNT <= 0)
  THEN
   EXECUTE IMMEDIATE
    'CREATE SEQUENCE LAB3_ROZGHON_MARK_SEQ
      MINVALUE 1
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
 END IF;

 SELECT COUNT(*) INTO NCOUNT FROM DBA_SEQUENCES WHERE SEQUENCE_NAME = 'LAB3_ROZGHON_USER_SEQ';
 IF(NCOUNT <= 0)
 THEN
     EXECUTE IMMEDIATE
         'CREATE SEQUENCE LAB3_ROZGHON_USER_SEQ
             MINVALUE 2
             START WITH 2
             INCREMENT BY 1
             NOCACHE';
 END IF;
END;
